const fs = require('fs');
const path = require('path');
const postgres = require('postgres');
require('dotenv').config({ path: path.join(__dirname, '../.env.local') });

function escape(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
}

async function main() {
  const sql = postgres(process.env.DATABASE_URL, { ssl: 'require' });
  const out = [];
  out.push('-- seed-data.sql snapshot — auto-generated by scripts/export-seed.js');
  out.push(`-- Generated: ${new Date().toISOString()}`);
  out.push('');
  try {
    const tables = [
      { name: 'brands', cols: ['id', 'name', 'country_of_origin', 'pharmacy_brand_flag'] },
      { name: 'ingredients', cols: ['id', 'name', 'eu_only_flag', 'notes'] },
      { name: 'products', cols: ['id', 'name', 'brand_id', 'category', 'description', 'what_its_good_for', 'why_buy_in_france', 'cult_favorite_flag', 'france_only_flag', 'tiktok_trending_flag', 'deal_flag', 'image_url'] },
      { name: 'prices', cols: ['id', 'product_id', 'price_eur_min', 'price_eur_max', 'price_usd_estimate'] },
      { name: 'us_availability', cols: ['id', 'product_id', 'availability_status', 'notes'] },
      { name: 'product_ingredients', cols: ['id', 'product_id', 'ingredient_id', 'highlight_flag'] },
      { name: 'review_summaries', cols: ['id', 'product_id', 'source_type', 'ai_summary_text'] },
    ];
    for (const t of tables) {
      const rows = await sql.unsafe(`SELECT ${t.cols.join(', ')} FROM ${t.name}`);
      out.push(`-- ${t.name} (${rows.length})`);
      for (const row of rows) {
        const vals = t.cols.map(c => escape(row[c]));
        out.push(`INSERT INTO public.${t.name} VALUES (${vals.join(', ')});`);
      }
      out.push('');
    }
    fs.writeFileSync(path.join(__dirname, '../seed-data.sql'), out.join('\n'));
    console.log(`Wrote seed-data.sql (${out.length} lines)`);
  } finally {
    await sql.end();
  }
}
main().catch(e => { console.error(e); process.exit(1); });
